name: CICD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build Svelte App
        run: |
          cd web
          npm ci
          npm run build

      - name: Build Go App
        run: |
          go mod tidy
          GOOS=linux GOARCH=amd64 go build -o albionstats .

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PI_SSH_KEY }}" > ~/.ssh/pi_id_ed25519
          chmod 600 ~/.ssh/pi_id_ed25519
          
          cat <<EOF > ~/.ssh/config
          Host pi
            HostName localhost
            User ${{ secrets.PI_USER }}
            IdentityFile ~/.ssh/pi_id_ed25519
            UserKnownHostsFile=/dev/null
            StrictHostKeyChecking no
            ProxyCommand cloudflared access ssh --id ${{ secrets.CF_ACCESS_CLIENT_ID }} --secret ${{ secrets.CF_ACCESS_CLIENT_SECRET }} --hostname ${{ secrets.PI_HOST }}
          EOF

      - name: Install cloudflared
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared
          sudo mv cloudflared /usr/local/bin/
          
      - name: Deploy files to Raspberry Pi
        run: |
          scp albionstats pi:/usr/local/bin/albionstats_temp
          scp -r web/build pi:/usr/local/share/albionstats_web_temp

      - name: Atomic deployment
        run: |
          ssh pi "sudo systemctl stop albionstats"
          ssh pi "sudo rm -rf /usr/local/share/albionstats_web && sudo mv /usr/local/share/albionstats_web_temp /usr/local/share/albionstats_web"
          ssh pi "sudo mv /usr/local/bin/albionstats_temp /usr/local/bin/albionstats && sudo chmod +x /usr/local/bin/albionstats"
          ssh pi "sudo systemctl start albionstats"
